apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: linkerd
spec:
  releaseName: linkerd 
  chart:
    repository: https://helm.linkerd.io/stable
    version: latest
