apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: db
spec:
  releaseName: redis 
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: 10.6.0
  values:
    usePassword: false
