apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: redis
  namespace: db
spec:
  releaseName: redis 
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: redis
    version: latest
  values:
    generateBasicAuth: true
    serviceType: LoadBalancer
    operator:
      create: true
